# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 14:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('oss_main', '0002_auto_20160509_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login_name',
        ),
        migrations.AddField(
            model_name='user',
            name='url',
            field=models.URLField(default=datetime.datetime(2016, 5, 9, 14, 28, 51, 267738, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(),
        ),
    ]
