# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oss_main', '0002_auto_20160509_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='url',
            new_name='git_url',
        ),
    ]
