# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oss_main', '0003_auto_20160509_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='url',
            field=models.URLField(max_length=250),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='url',
            field=models.URLField(max_length=250),
        ),
    ]
