# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oss_main', '0003_auto_20160509_1428'),
        ('admin', '0002_logentry_remove_auto_add'),
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
