# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='IssueDeveloper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='IssueSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oss_main.Issue')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('url', models.URLField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40)),
                ('password', models.CharField(max_length=80)),
                ('login_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oss_main.Level')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oss_main.Skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oss_main.User')),
            ],
        ),
        migrations.AddField(
            model_name='projectowner',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oss_main.User'),
        ),
        migrations.AddField(
            model_name='projectowner',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oss_main.Project'),
        ),
        migrations.AddField(
            model_name='issueskill',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oss_main.Level'),
        ),
        migrations.AddField(
            model_name='issueskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oss_main.Skill'),
        ),
        migrations.AddField(
            model_name='issuedeveloper',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oss_main.User'),
        ),
        migrations.AddField(
            model_name='issuedeveloper',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oss_main.Issue'),
        ),
        migrations.AddField(
            model_name='issue',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oss_main.User'),
        ),
        migrations.AddField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oss_main.Project'),
        ),
    ]
