# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oss_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='git_url',
            field=models.URLField(blank=True),
        ),
    ]
