# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oss_main', '0002_auto_20160515_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
