# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 10:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oss_main', '0003_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='github_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='projectowner',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectowner',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='oss_main.Project'),
        ),
    ]
